#deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: city-manage-api
spec:
  selector:
    matchLabels:
      app: city-manage-api
  replicas: 1
  template:
    metadata:
      labels:
        app: city-manage-api
    spec:
      containers:
      - name: city-manage-api
        args:
        image: registry-vpc.cn-shanghai.aliyuncs.com/jiadx/apps:city-manage-api-3.3.3-v21 
        ports:
        - containerPort: 8085
        env:
        - name: aliyun_logs_city-manage-api
          value: "/opt/logs/city-manage-api/log.log4j"
        volumeMounts:
        - name: logs
          mountPath: /opt/logs/city-manage-api/
        readinessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 20
          periodSeconds: 20
      volumes:
      - name: logs
        emptyDir: {}
      imagePullSecrets:
      - name: regsecret
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

---
#service
apiVersion: v1
kind: Service
metadata:
  name: city-manage-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8085 
  selector:
    app: city-manage-api
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: city-manage-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_method = 'OPTIONS') {
              add_header 'Access-Control-Allow-Origin' * always;
              add_header 'Access-Control-Allow-Credentials' 'true';
              add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
              add_header 'Access-Control-Max-Age' '3600';
              add_header 'Access-Control-Allow-Headers' 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-SESSIONID';
              return 200;
       }
      if ($request_method = 'POST') {
              add_header      'Access-Control-Allow-Origin'   * always;
              add_header  'Access-Control-Allow-Credentials' 'true';
              add_header  'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
              add_header  'Access-Control-Max-Age' '3600';
              add_header      'Access-Control-Allow-Headers'  'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-SESSIONID';
      }
      rewrite /city-manage-api($|.*) /city-manage-api$1 break;
spec:
  rules:
  - host: api.jiaofajituan.com
    http:
      paths:
      - path: /city-manage-api(/|$)(.*)
        backend:
          serviceName: city-manage-api
          servicePort: 80
